## ??/?? ?? ??

jwt:
  access-token:
    expiry: ${ACCESS_TOKEN_EXPIRY}
  refresh-token:
    expiry: ${REFRESH_TOKEN_EXPIRY}
  jwk-set-uri : ${JWK_SET_URI}

jwk:
  private-key-path: ${JWK_PRIVATE_KEY_PATH}
  public-key-path: ${JWK_PUBLIC_KEY_PATH}

oauth2:
  registrar-client:
    id: ${REGISTRAR_CLIENT_ID}
    secret: ${REGISTRAR_CLIENT_SECRET}